### ISSUE TITLE
Decreasing the numVfs in the policy doesn't seem to work

### ISSUE THREAD

**Issue by e-minguez** [openshift/sriov-network-operator#131]
I've deployed the sriov operator and created a policy with the following yaml:
```
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: eno1-network-node-policy
  namespace: openshift-sriov-network-operator
spec:
  deviceType: netdevice
  isRdma: false
  mtu: 1500
  nicSelector:
    pfNames:
    - eno1
    rootDevices:
    - 0000:01:00.0
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  numVfs: 63
  priority: 10
  resourceName: sriovnics
```

Tested a sriovnetwork, pods with the net-attach-def with static ips and everything works. Now I want to decrease the numVfs, so I've edited the resource and set it to 4:

```
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: eno1-network-node-policy
  namespace: openshift-sriov-network-operator
spec:
  deviceType: netdevice
  isRdma: false
  mtu: 1500
  nicSelector:
    pfNames:
    - eno1
    rootDevices:
    - 0000:01:00.0
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  numVfs: 4
  priority: 10
  resourceName: sriovnics
```

But in the actual hosts the number of VFs is still the same. I've tried to manually resize them with:

```
# echo 4 > /sys/class/net/eno1/device/sriov_numvfs
-bash: echo: write error: Device or resource busy
```

And in dmesg:

```
[177015.556541] ixgbe 0000:01:00.0: 63 VFs already enabled. Disable before enabling 4 VFs
```

So I'm assuming it needs to be disabled/enabled.

Thanks.
