### ISSUE TITLE
DeviceType: vfio-pci is not recognized  on OKD 4.6 

### ISSUE THREAD

**Issue by rupang790** [openshift/sriov-network-operator#463]
My cluster version is "4.6.0-0.okd-2021-01-17-185703" and I tried to use SR-IOV for KubeVirt vm.
On OpenShift official documents, only vfio-pci deviceType can be used for KubeVirt vm.
So I installed openshift-sriov-network-operator plugin by manual (git clone and make deploy-setup) and turned off web hook to use unsupported NIC  as below:
![image](https://user-images.githubusercontent.com/40801176/105308048-f7603e80-5bff-11eb-8d68-078913a06631.png)

After I configured host's /etc/default/grub file, executed mkconfig and rebooted the host, I can see the VFIO modules from lsmod command results. So I created sriov-network-policy yaml file, but it seems not created VFs as I want.

**[sriov-device-plugin pod logs]**
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/40801176/105309316-473f0580-5c00-11eb-9add-8cfb0b986315.png">

Do anyone have idea to fix it?
I share my configurations and information as below to help your understand:

- **OS**: Fedora CoreOS 33.20210104.10.0
- **OKD version**: 4.6.0-0.okd-2021-01-17-185703
- **Used Branch**: master

```
# cat /etc/default/grub
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="intel_iommu=on iommu=pt rd.driver.pre=vfio-pci"
GRUB_DISABLE_RECOVERY="true"``


# cat np-sriov-vfio.yaml
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: ens3f1-vfio-np
  namespace: openshift-sriov-network-operator
spec:
  resourceName: ens3f1vfio
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  priority: 99
  mtu: 1500
  numVfs: 4
  nicSelector:
    vendor: "8086"
    deviceID: "10fb"
    pfNames: ["ens3f1#0-3"]
    rootDevices: ["0000:08:00.1"]
  deviceType: vfio-pci
  isRdma: false

**Comment by rupang790** [comment]
What I missed for using VFIO module for SR-IOV?
I share my configuration on Host server about VFIO modules.

```
# cat /etc/default/grub
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="intel_iommu=on iommu=pt rd.driver.pre=vfio-pci"
GRUB_DISABLE_RECOVERY="true"

# echo 'vfio' > /etc/modules-load.d/vfio.conf
# echo 'vfio-pci' > /etc/modules-load.d/vfio-pci.conf
# echo 'vfio_iommu_type1' > /etc/modules-load.d/vfio_iommu_type1.conf
# echo 'vfio_virqfd' > /etc/modules-load.d/vfio_virqfd.conf
```

After reboot the host(worker), I tried to create 4VFs by NetworkPolicy.yaml file as below:
```
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: ens3f1-vfio-np
  namespace: openshift-sriov-network-operator
spec:
  resourceName: ens3f1vfio
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  priority: 99
  mtu: 1500
  numVfs: 4
  nicSelector:
    vendor: "8086"
    deviceID: "10fb"
    pfNames: ["ens3f1#0-3"]
    rootDevices: ["0000:08:00.1"]
  deviceType: vfio-pci
  isRdma: false
```

Even though I define the "deviceType" as vfio-pci, "DeviceType: netDevice" keep logging on sriov-device-plugin-xxxxx pod as:
![image](https://user-images.githubusercontent.com/40801176/105662880-259d9100-5f14-11eb-815c-d6e9a7a54a05.png)

What am I missing for vfio and IOMMU setting on host server? 
Please help :(
