### ISSUE TITLE
Unsupported value: "requests.hugepages-1Gi"

### ISSUE THREAD

**Issue by rupang790** [openshift/sriov-network-operator#514]
Hi, I would like to use SR-IOV network with HugePages but no with DPDK.
My environment is:
- OKD Cluster : 4.5.0-0.okd-2020-10-15-235428
- SR-IOV Operator Version : 4.7.0
- NIC : Intel NIC
- HugePage on Node
```
$ oc get node worker01.eluon.okd.com -o jsonpath="{.status.allocatable.hugepages-1Gi}"
10Gi
```

I followed to configure HugePage on Node, then create SR-IOV NetworkAttachmentDefinition and pod as below:

SriovNetworkNodePolicy
```
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: ens3f1-netdev
  namespace: openshift-sriov-network-operator
spec:
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
    kubernetes.io/hostname: worker01.eluon.okd.com
  resourceName: ens3f1net
  numVfs: 4
  nicSelector:
    deviceID: "10fb"
    rootDevices: ["0000:13:00.1"]
    vendor: "8086"
    pfNames: ["ens3f1#0-3"]
  deviceType: netdevice
```

SriovNetwork
```
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: ens3f1-netdev
  namespace: openshift-sriov-network-operator
spec:
  resourceName: ens3f1net
  networkNamespace: default
  ipam: '{
    "type": "static",
    "addresses": [
    {
      "address": "192.168.10.30/24"
    }],
    "routes": [
    {
      "dst": "192.168.10.0/24",
      "gw": "192.168.10.100"
    }]
  }'
  capabilities: '{ "ips": true }'
```

Pod
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-sriov-hp-test
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: default/ens3f1-netdev
spec:
  nodeSelector:
    kubernetes.io/hostname: worker01.eluon.okd.com
  hostname: test-sriov-hp
  containers:
  - name: test-container
    command: ["/bin/bash", "-c", "sleep 200000000"]
    image: centos/tools:latest
    resources:
      limits:
        openshift.io/ens3f1net: "1"
        hugepages-1Gi: "1Gi"
        memory: 2Gi
      requests:
        openshift.io/ens3f1net: "1"
        hugepages-1Gi: "1Gi"
        memory: 2Gi
    securityContext:
      privileged: true
    volumeMounts:
      - name: hugepages
        mountPath: /dev/hugepages
  volumes:
  - name: hugepages
    hostPath:
      path: /dev/hugepages
```

But error as below occurred:
```
The Pod "pod-sriov-hp-test" is invalid:
* spec.volumes[2].downwardAPI.resourceFieldRef.resource: Unsupported value: "requests.hugepages-1Gi": supported values: "limits.cpu", "limits.ephemeral-storage", "limits.memory", "requests.cpu", "requests.ephemeral-storage", "requests.memory"
* spec.volumes[2].downwardAPI.resourceFieldRef.resource: Unsupported value: "limits.hugepages-1Gi": supported values: "limits.cpu", "limits.ephemeral-storage", "limits.memory", "requests.cpu", "requests.ephemeral-storage", "requests.memory"
* spec.containers[0].volumeMounts[2].name: Not found: "podnetinfo"
```

What I test for this:
- Exclude annotations -> SR-IOV VF is not attached on Pod
- Exclude 'openshift.io/ens3f1net' from resources -> [Unsupported value: "requests.hugepages-1Gi"] occurred
- Add Download API for HugePage (Reference: https://docs.okd.io/latest/scalability_and_performance/what-huge-pages-do-and-how-they-are-consumed-by-apps.html) -> error as below:
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/40801176/121618551-eb3b2780-caa1-11eb-93e8-c0125bda36e9.png">

I already check SR-IOV which use DPDK is working well with HugePage configuration, but it is not working for SR-IOV which is not use DPDK case. Do you have any information about this?
(I am not sure this error is related to SR-IOV Operator or OKD Cluster.)
