### ISSUE TITLE
Device ID selector is not working correctly

### ISSUE THREAD

**Issue by Mmduh-483** [openshift/sriov-network-operator#60]
Adding a `deviceID` selector to the node policy, with VF device ID, will not filter out all the PFs, this is related to the hardcoded supported device and the filtering mechanism 
```
var SriovPfVfMap = map[string](string){
        "1583": "154c",
        "10fb": "10ed",
        "1015": "1016",
        "1017": "1018",
}
```

```
if s.NicSelector.DeviceID != "" {
                if ((s.NumVfs == 0 && s.NicSelector.DeviceID != iface.DeviceID) || (s.NumVfs > 0 && s.NicSelector.DeviceID != SriovPfVfMap[iface.DeviceID])) {
                        return false
                }
        }
```

I tried the following node policy but got no changes

```
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: policy-2
  namespace: sriov-network-operator
spec:
  resourceName: mlxnics
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  priority: 4
  mtu: 9000
  numVfs: 8
  nicSelector:
    vendor: "15b3"
    deviceID: "1018"
    rootDevices: ['0000:04:00.0', '0000:04:00.1']
  deviceType: netdevice
  isRdma: true
```
