### ISSUE TITLE
network-resources-injector and operator-webhook daemonset should have configurable tolerations

### ISSUE THREAD

**Issue by korroot** [openshift/sriov-network-operator#679]
Master nodes of Kubernetes 1.23 in my deployment have following taints:
```
spec:
(...)
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
```
I am not able to spawn daemonsets that are created by sriov-operator, becasue of hardcoded tolerations:

```
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
```
https://github.com/openshift/sriov-network-operator/blob/5c2581ddd7843433f4cd3ce80938f766d49326fd/bindata/manifests/webhook/server.yaml#L42-L48

To enable `network-resources-injector` and `operator-webhook` deployments, those tolerations should be configurable.

**Comment by hudymi** [comment]
It doesn't have to be configurable. It can be generic:

```yaml
 tolerations: 
 - operator: Exists 
   effect: NoSchedule 
 - operator: Exists 
   effect: NoExecute 
```
