### ISSUE TITLE
Worker="" vs Worker="foo"

### ISSUE THREAD

**Issue by ns-rlewkowicz** [openshift/sriov-network-operator#829]
Our worker nodes are tagged with `node-role.kubernetes.io/worker: "true"` and I believe with how this is written, that matters. 

[                "node-role.kubernetes.io/worker": "",](https://github.com/openshift/sriov-network-operator/blob/0055add05e9893a6db28238b31b3abd139f268a7/controllers/sriovnetworknodepolicy_controller.go#L125)

Looks like there's a config option I'll take a closer look at. Ideally it would just check for the presence of the label, not the value.

**Comment by ns-rlewkowicz** [comment]
That worked
```
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovOperatorConfig
metadata:
  annotations:
  name: default
  namespace: sriov-network-operator
spec:
  configDaemonNodeSelector:
    node-role.kubernetes.io/worker": "true"
  enableInjector: true
  enableOperatorWebhook: false
  logLevel: 2
```

But now I have issues with the other DS. Node selectors work on a fresh minikube install, but this is troublesome to incorporate into an existing environment. 

I need more control for node selectors globally
